export enum STUDENT {
    STUDENT_PROFILE_FETCH = 'STUDENT_PROFILE_FETCH',
    STUDENT_PROFILE_FETCH_OK = 'STUDENT_PROFILE_FETCH_OK',
    STUDENT_PROFILE_FETCH_FAIL = 'STUDENT_PROFILE_FETCH_FAIL',
}

export enum MENTOR {
    MENTOR_PROFILE_FETCH = 'MENTOR_PROFILE_FETCH',
    MENTOR_PROFILE_FETCH_OK = 'MENTOR_PROFILE_FETCH_OK',
    MENTOR_PROFILE_FETCH_FAIL = 'MENTOR_PROFILE_FETCH_FAIL',
}
